# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/hugo
image: jojomi/hugo:latest

variables:
  # make sure themes submodules are fetched
  #GIT_SUBMODULE_STRATEGY: recursive

before_script:
  # make sure themes submodules are fetched
  - apk add git -y
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - cd themes/casadi-theme
  - apk add --update nodejs
  - npm install -g gulp
  - npm install gulp-sass gulp-autoprefixer gulp-rename gulp-bower gulp-minifier --save
  - gulp bower
  - gulp icons
  - gulp scss

pages:
  tags:
    - pages
  script:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master

test:
  tags:
    - pages
  script:
    - hugo
  except:
    - master
