baseURL = "https://u0102655.pages.mech.kuleuven.be/hugo-casadi/"
languageCode = "en-us"
title = "CasADi"
theme = "casadi-theme"
googleAnalytics = ""

# [permalinks]
#   singles = "/:title/"

[permalinks]
  # blog = "/blog/:year/:month/:day/:title/"

[params]
  author = "Joris Gillis, Armin Steinhauser"
  copyright = "Copyright 2018."
  logo = "/img/logo_2017_horizontal.svg"
  motto = "Peak performance, automatically."
  DocsHeader = "Docs v3.3.0"
  pygmentsUseClassic = true
  pygmentsUseClasses = true

[blackfriday]
  # extensions = ["hardLineBreak", "noIntraEmphasis"]
  # extensions = ["hardLineBreak"]
  # extensionsmask = ["autoHeaderIds"]

[menu]
  # [[menu.main]]
  #   url = "/"
  #   name = "Home"
  #   identifier = "home"
  #   weight = 1

  [[menu.main]]
    url = "/get-casadi/"
    name = "Get CasADi"
    identifier = "get-casadi"
    weight = 2

  [[menu.main]]
    url = "/blog/"
    name = "Blog"
    identifier = "blog"
    weight = 3

  [[menu.main]]
    url = "/docs/"
    name = "Docs"
    identifier = "docs"
    weight = 4

  [[menu.main]]
    url = "/about/"
    name = "About"
    identifier = "about"
    weight = 5

  [[menu.main]]
    url = "/support/"
    name = "Support"
    identifier = "support"
    weight = 6

  # docs
  # [[menu.docs]]
  #   url = "/docs/get-casadi/"
  #   name = "Get CasADi"
  #   identifier = "get-casadi"
  #   weight = 1
  # [[menu.docs]]
  #   url = "/docs/get-started/"
  #   name = "Get started"
  #   identifier = "get-started"
  #   weight = 1

  # Footer
  # [[menu.footer]]
  #   url = "mailto:me@example.com"
  #   name = "envelope-o"
  #   weight = 1

  [[menu.footer]]
    url = "https://github.com/casadi/casadi"
    name = "github"
    weight = 2

  [[menu.footer]]
    url = "https://twitter.com/casadi_software"
    name = "twitter"
    weight = 3

  # [[menu.footer]]
  #   url = "https://github.com/username/"
  #   name = "linkedin"
  #   weight = 4
