baseURL = "http://www.casadi.org/"
languageCode = "en-us"
title = "CasADi"
theme = "casadi-theme" #"casadi-theme"
googleAnalytics = ""

[permalinks]
  singles = "/:title/"

[params]
  # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
  # style = "red"
    author = "Joris Gillis, Armin Steinhauser"
    copyright = "Copyright 2017."
    description = "Peak performance, automatically."
    # githubUsername = "#"
    # accent = "red"
    # showBorder = true
    # backgroundColor = "white"
    # font = "Raleway" # should match the name on Google Fonts!
    # highlight = true
    # highlightStyle = "solarized-dark"
    # highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    mainIcon = "/img/casadi.svg"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1
    icon = "none"

[[menu.main]]
    url = "/get-casadi/"
    name = "Get CasADi"
    weight = 2

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 3

[[menu.main]]
    url = "/docs/"
    name = "Docs"
    weight = 4

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 5

[[menu.main]]
    url = "/support/"
    name = "Support"
    weight = 6

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/
[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "github"
    weight = 2
