baseURL = "http://www.casadi.org/"
languageCode = "en-us"
title = "CasADi"
theme = "casadi-theme"
googleAnalytics = ""

[permalinks]
  singles = "/:title/"

[params]
  author = "Joris Gillis, Armin Steinhauser"
  copyright = "Copyright 2017."
  logo = "/img/logo_2017_horizontal.svg"
  motto = "Peak performance, automatically."

[[menu.main]]
  url = "/"
  name = "Home"
  weight = 1

[[menu.main]]
  url = "/get-casadi/"
  name = "Get CasADi"
  weight = 2

[[menu.main]]
  url = "/blog/"
  name = "Blog"
  weight = 3

[[menu.main]]
  url = "/docs/"
  name = "Docs"
  weight = 4

[[menu.main]]
  url = "/about/"
  name = "About"
  weight = 5

[[menu.main]]
  url = "/support/"
  name = "Support"
  weight = 6

# Footer
[[menu.footer]]
  url = "mailto:me@example.com"
  name = "envelope-o"
  weight = 1

[[menu.footer]]
  url = "https://github.com/username/"
  name = "github"
  weight = 2

[[menu.footer]]
  url = "https://github.com/username/"
  name = "twitter"
  weight = 3

[[menu.footer]]
  url = "https://github.com/username/"
  name = "linkedin"
  weight = 4
