name: compose

on: push

env:
  version: "3.6.0"

jobs:
  main:
    runs-on: ubuntu-22.04

    steps:

    - uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0 # for git-restore-mtime
    
    - name: script
      run: |
        sed -i "s/casadi_release = \"3.5.5\"/casadi_release = \"nightly-release-${{ env.version }}\"/" config.toml
        sed -i "s/casadi_version = \"3.5.5\"/casadi_version = \"${{ env.version }}\"/" config.toml
        cat config.toml
        wget -q https://github.com/casadi/casadi/releases/download/nightly-release-${{ env.version }}/website_assets.zip
        unzip -oq website_assets.zip
        ls -al
        ./run_build.sh

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1.0.8
      with:
        path: ./public
        

          
